name: dream
description: An api application
version: 1.0.2+4
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dio: ^5.4.3+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shelf_cors_headers: ^0.1.5
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0
